import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { AppHeader } from '@/components/ui';
import { colors } from '@/constants/colors';
import { useAuth } from '@/context/auth-context';
import { api, CollectionAnalytics, School } from '@/lib/api';

const ranges = ['daily','weekly','monthly','custom'] as const;

export default function CollectionsScreen(){
  const {session}=useAuth();const school=session?.role==='admin'?session.user as School:undefined;
  const [range,setRange]=useState<(typeof ranges)[number]>('monthly'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[data,setData]=useState<CollectionAnalytics>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async(selected=range)=>{if(selected==='custom'&&(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)))return setError('Enter both dates as YYYY-MM-DD.');setBusy(true);setError('');try{setData(await api.getCollectionAnalytics(selected,selected==='custom'?from:undefined,selected==='custom'?to:undefined));}catch(caught){setError(caught instanceof Error?caught.message:'Could not load collection.');}finally{setBusy(false)}};
  useEffect(()=>{void load('monthly')},[]);
  const choose=(value:(typeof ranges)[number])=>{setRange(value);if(value!=='custom')void load(value)};
  return <View style={styles.page}><AppHeader back school={school}/><ScrollView contentContainerStyle={styles.scroll}><View style={styles.hero}><Text style={styles.kicker}>FINANCE INSIGHTS</Text><Text style={styles.title}>Total collection</Text><Text style={styles.copy}>Live totals calculated from paid monthly and exam fee entries.</Text></View><View style={styles.tabs}>{ranges.map(value=><Pressable key={value} onPress={()=>choose(value)} style={[styles.tab,range===value&&styles.tabActive]}><Text style={[styles.tabText,range===value&&styles.tabTextActive]}>{value[0].toUpperCase()+value.slice(1)}</Text></Pressable>)}</View>{range==='custom'&&<View style={styles.custom}><TextInput style={styles.input} placeholder="From · YYYY-MM-DD" value={from} onChangeText={setFrom} keyboardType="numbers-and-punctuation"/><TextInput style={styles.input} placeholder="To · YYYY-MM-DD" value={to} onChangeText={setTo} keyboardType="numbers-and-punctuation"/><Pressable style={styles.apply} onPress={()=>void load('custom')}><Text style={styles.applyText}>Apply dates</Text></Pressable></View>}{error?<Text style={styles.error}>{error}</Text>:null}{busy?<ActivityIndicator color={colors.gold}/>:<View style={styles.metrics}><Metric label="TOTAL COLLECTED" value={data?.total||0} copy={`${data?.entries||0} paid entries`} primary/><Metric label="MONTHLY FEES" value={data?.monthly||0} copy="Tuition collection"/><Metric label="EXAM FEES" value={data?.exam||0} copy="Assessment collection"/></View>}<Text style={styles.note}>Only payments whose payment date falls inside the selected period are included.</Text></ScrollView></View>
}
function Metric({label,value,copy,primary=false}:{label:string;value:number;copy:string;primary?:boolean}){return <View style={[styles.metric,primary&&styles.primary]}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.value,primary&&styles.valuePrimary]}>₹{Number(value).toLocaleString('en-IN')}</Text><Text style={[styles.metricCopy,primary&&styles.copyPrimary]}>{copy}</Text></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.cream},scroll:{padding:18,paddingBottom:44,gap:16},hero:{backgroundColor:colors.ink,borderRadius:24,padding:22,gap:7},kicker:{color:colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.8},title:{color:'#fff',fontSize:31,fontWeight:'900'},copy:{color:'#ded7cb',lineHeight:20},tabs:{flexDirection:'row',flexWrap:'wrap',gap:8},tab:{flexGrow:1,minWidth:'45%',borderWidth:1,borderColor:colors.line,backgroundColor:colors.paper,borderRadius:14,padding:13},tabActive:{backgroundColor:colors.ink},tabText:{textAlign:'center',color:colors.muted,fontWeight:'800'},tabTextActive:{color:'#fff'},custom:{gap:10,backgroundColor:colors.paper,padding:14,borderRadius:18,borderWidth:1,borderColor:colors.line},input:{height:52,borderWidth:1,borderColor:colors.line,borderRadius:13,paddingHorizontal:14,color:colors.ink,backgroundColor:'#fff'},apply:{backgroundColor:colors.gold,borderRadius:13,padding:15},applyText:{textAlign:'center',fontWeight:'900',color:colors.ink},metrics:{gap:12},metric:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:20,padding:20,gap:7},primary:{backgroundColor:colors.ink},metricLabel:{color:colors.gold,fontWeight:'900',fontSize:10,letterSpacing:1.2},value:{fontSize:30,fontWeight:'900',color:colors.ink},valuePrimary:{color:'#fff'},metricCopy:{color:colors.muted},copyPrimary:{color:'#ded7cb'},error:{color:colors.danger,fontWeight:'800',backgroundColor:'#fce8e4',padding:12,borderRadius:12},note:{color:colors.muted,fontSize:11,lineHeight:17,textAlign:'center'}});
