import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "../supabaseClient";
import { CalendarCheck, CircleDollarSign, Clock3, ReceiptIndianRupee } from "lucide-react";
import "./AdminStudentFees.css";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

const months=["March","April","May","June","July","August","September","October","November","December","January","February"];
const paidFor=fee=>fee.paid_amount!==undefined?Number(fee.paid_amount):fee.status==="Paid"?Math.max(0,Number(fee.amount||0)+Number(fee.carried_due||0)-Number(fee.due_amount||0)):0;
export default function AdminStudentFees(){
  const{id}=useParams();const[fees,setFees]=useState([]),[student,setStudent]=useState(JSON.parse(localStorage.getItem("selectedStudent")||"null")),[school,setSchool]=useState({}),[syncing,setSyncing]=useState(true),[view,setView]=useState("monthly"),[selectedExam,setSelectedExam]=useState("");
  const adminSchool=JSON.parse(localStorage.getItem("schoolData")||localStorage.getItem("adminData")||"{}");
  const load=async()=>{setSyncing(true);const studentRequest=student?.id===id?Promise.resolve({data:student}):supabase.from("students").select("*").eq("id",id).eq("school_code",adminSchool.school_code).single();const[{data:studentData},{data:existing}]=await Promise.all([studentRequest,supabase.from("fees").select("*").eq("student_id",id)]);if(!studentData){setSyncing(false);return}setStudent(studentData);const{data:schoolData}=await supabase.from("schools").select("*").eq("school_code",studentData.school_code).single();setSchool(schoolData||{});const monthly=months.map(month=>({student_id:id,school_code:studentData.school_code,fee_type:"monthly",month,amount:Number(schoolData?.monthly_fees?.[studentData.class]||0),carried_due:0,due_amount:0,paid_amount:0,status:"Pending"}));const exams=(schoolData?.exam_fees||[]).map(item=>({student_id:id,school_code:studentData.school_code,fee_type:"exam",exam_fee_id:item.id,title:`${item.name} · ${item.type}`,month:item.name,amount:Number(item.class_amounts?.[studentData.class]||0),carried_due:0,due_amount:0,paid_amount:0,status:"Pending"}));let records=existing||[];const response=await supabase.from("fees").insert([...monthly,...exams]);if(!response.error)records=response.data||records;records=[...records.filter(fee=>(fee.fee_type||"monthly")==="monthly").sort((a,b)=>months.indexOf(a.month)-months.indexOf(b.month)),...records.filter(fee=>fee.fee_type==="exam")].map(fee=>({...fee,paid_amount:paidFor(fee)}));setFees(records);setSelectedExam(current=>current||records.find(fee=>fee.fee_type==="exam")?.exam_fee_id||"");setSyncing(false)};
  useEffect(()=>{load()},[id]);
  const save=async(fee,status)=>{const total=Number(fee.amount||0)+Number(fee.carried_due||0),paid=Math.min(total,Math.max(0,Number(fee.paid_amount||0))),balance=Math.max(0,total-paid),changes={status,paid_amount:paid,due_amount:balance,dues_paid:balance===0,paid_at:status==="Paid"&&paid>0?new Date().toISOString():""};setFees(current=>current.map(item=>item.id===fee.id?{...item,...changes,updating:true}:item));const{error}=await supabase.from("fees").update(changes).eq("id",fee.id).eq("student_id",id);if(error){alert(error.message||"Fee update failed");return load()}if((fee.fee_type||"monthly")==="monthly"){const rows=fees.filter(item=>(item.fee_type||"monthly")==="monthly").sort((a,b)=>months.indexOf(a.month)-months.indexOf(b.month)),next=rows[rows.findIndex(item=>item.id===fee.id)+1];if(next?.id)await supabase.from("fees").update({carried_due:balance}).eq("id",next.id).eq("student_id",id)}await load()};
  const paidCount=useMemo(()=>fees.filter(fee=>fee.status==="Paid").length,[fees]);const exams=fees.filter(fee=>fee.fee_type==="exam"),visible=view==="monthly"?fees.filter(fee=>(fee.fee_type||"monthly")==="monthly"):exams.filter(fee=>fee.exam_fee_id===selectedExam);
  if(student&&adminSchool.school_code&&student.school_code!==adminSchool.school_code)return <div className="workspace-error">This student does not belong to your school.</div>;
  return <main className="fees-page-shell"><header className="finance-brand"><img src={school.school_logo||student?.school_logo||"/brand-mark.svg"} alt=""/><div><small>FINANCE DESK · SCHOOL CODE {student?.school_code||"—"}</small><h1>{school.school_name||student?.school_name||"School fees"}</h1><p>{student?.name||"Student"} · Class {student?.class||"—"}-{student?.section||"—"} · Roll {student?.roll||"—"}</p></div><ReceiptIndianRupee/></header><section className="fees-premium-card"><div className="fees-title"><div><small>ACADEMIC SESSION</small><h2>Fee ledger</h2></div>{syncing&&<span className="sync-badge">Syncing…</span>}</div><div className="fees-summary premium-fee-summary"><div><CalendarCheck/><span><b>{paidCount}</b><small>Paid entries</small></span></div><div><Clock3/><span><b>{fees.length-paidCount}</b><small>Pending entries</small></span></div><div><CircleDollarSign/><span><b>{fees.length}</b><small>Total entries</small></span></div></div><div className="fee-ledger-tabs"><button className={view==="monthly"?"active":""} onClick={()=>setView("monthly")}>Monthly</button><button className={view==="exam"?"active":""} onClick={()=>setView("exam")}>Exam</button></div>{view==="exam"&&<select className="exam-fee-select" value={selectedExam} onChange={event=>setSelectedExam(event.target.value)}>{exams.map(fee=><option key={fee.id} value={fee.exam_fee_id}>{fee.title||fee.month}</option>)}</select>}<div className="premium-fee-grid">{visible.map(fee=>{const base=Number(fee.amount||0),carry=Number(fee.carried_due||0),total=base+carry,paid=Math.min(total,Math.max(0,Number(fee.paid_amount||0))),balance=Math.max(0,total-paid);return <article key={fee.id} className={fee.status==="Paid"?"is-paid":"is-pending"}><div className="fee-month"><small>{fee.fee_type==="exam"?"EXAM FEE":"MONTH"}</small><b>{fee.title||fee.month}</b><strong>₹{base.toLocaleString("en-IN")}</strong><small>Previous dues ₹{carry.toLocaleString("en-IN")}</small><b>Total payable ₹{total.toLocaleString("en-IN")}</b></div><div className="fee-state"><label>Paid amount ₹<input inputMode="numeric" value={fee.paid_amount??0} onChange={event=>setFees(current=>current.map(item=>item.id===fee.id?{...item,paid_amount:event.target.value.replace(/\D/g,"")}:item))}/></label><b>Total paid ₹{paid.toLocaleString("en-IN")}</b><small>Balance due ₹{balance.toLocaleString("en-IN")}</small><div className="fee-status-buttons"><button disabled={fee.updating} className={fee.status==="Pending"?"active":""} onClick={()=>save(fee,"Pending")}>Pending</button><button disabled={fee.updating} className={fee.status==="Paid"?"active paid":""} onClick={()=>save(fee,"Paid")}>Paid</button></div></div><div className="fee-date"><small>PAYMENT DATE</small><b>{fee.paid_at?new Date(fee.paid_at).toLocaleDateString("en-IN"):"Not paid"}</b></div></article>})}</div></section></main>;
}
