import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowRight, FileChartColumn, GraduationCap, MapPin, Phone, ReceiptIndianRupee, School, UserRound } from "lucide-react";
import { supabase } from "../supabaseClient";
import "./AdminStudentDashboard.css";

export default function AdminStudentDashboard(){
  const{id}=useParams();const navigate=useNavigate();const[student,setStudent]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const activeSchool=JSON.parse(localStorage.getItem("schoolData")||localStorage.getItem("adminData")||"{}");
  useEffect(()=>{(async()=>{const selected=JSON.parse(localStorage.getItem("selectedStudent")||"{}");if(selected.id===id&&selected.school_code===activeSchool.school_code){setStudent(selected);setLoading(false);return;}const{data,error:fetchError}=await supabase.from("students").select("*").eq("id",id).eq("school_code",activeSchool.school_code).single();if(fetchError||!data)setError("Student record could not be loaded");else{setStudent(data);localStorage.setItem("selectedStudent",JSON.stringify(data));}setLoading(false);})()},[id]);
  if(loading)return <div className="workspace-loading"><span></span><b>Opening student workspace…</b></div>;if(!student)return <div className="workspace-error">{error||"Student not found"}<button onClick={()=>navigate(-1)}>Go back</button></div>;
  const actions=[{title:"Student profile",copy:"View and update personal and academic information.",icon:UserRound,path:`/StudentProfile/${student.id}`},{title:"Fee ledger",copy:"Manage monthly payment status and paid dates.",icon:ReceiptIndianRupee,path:`/AdminStudentFees/${student.id}`},{title:"Exam results",copy:"Create, publish, edit and review examination results.",icon:FileChartColumn,path:`/AdminStudentResult/${student.id}`}];
  return <main className="student-record-shell"><header className="record-school-bar"><img src={student.school_logo||activeSchool.school_logo||"/brand-mark.svg"} alt=""/><div><small>SCHOOL STUDENT RECORD · CODE {student.school_code}</small><h2>{student.school_name||activeSchool.school_name}</h2></div><School/></header><section className="student-record-hero"><div className="record-photo"><img src={student.photo_url||"/brand-mark.svg"} alt={student.name}/><span><GraduationCap/></span></div><div className="record-identity"><small>ENROLLED STUDENT</small><h1>{student.name}</h1><p>{student.father_name?`S/O ${student.father_name}`:"Verified school student"}</p><div className="record-tags"><span><GraduationCap/> Class {student.class}-{student.section}</span><span>Roll {student.roll}</span></div></div><div className="record-contact"><span><Phone/><b>{student.number||"—"}</b></span><span><MapPin/><b>{student.address||"Address not added"}</b></span></div></section><section className="record-actions"><div className="record-section-heading"><div><small>STUDENT MANAGEMENT</small><h2>Academic workspace</h2></div><p>Select an area to continue managing this student.</p></div><div className="record-action-grid">{actions.map(({title,copy,icon:Icon,path})=><button key={title} onClick={()=>navigate(path)}><span><Icon/></span><div><h3>{title}</h3><p>{copy}</p></div><ArrowRight/></button>)}</div></section><footer className="record-footer"><GraduationCap/> All information is securely linked to {student.school_name||activeSchool.school_name}.</footer></main>;
}
