import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "../supabaseClient";
import { CalendarCheck, CircleDollarSign, Clock3, ReceiptIndianRupee } from "lucide-react";
import "./StudentFees.css";

const months=["March","April","May","June","July","August","September","October","November","December","January","February"];
const paidFor=fee=>fee.paid_amount!==undefined?Number(fee.paid_amount):fee.status==="Paid"?Math.max(0,Number(fee.amount||0)+Number(fee.carried_due||0)-Number(fee.due_amount||0)):0;
export default function StudentFees(){
  const{id}=useParams();const[fees,setFees]=useState([]),[student,setStudent]=useState({}),[school,setSchool]=useState({}),[loading,setLoading]=useState(true),[view,setView]=useState("monthly"),[selectedExam,setSelectedExam]=useState("");
  useEffect(()=>{(async()=>{setLoading(true);const[{data:studentData},{data:feeData}]=await Promise.all([supabase.from("students").select("*").eq("id",id).single(),supabase.from("fees").select("*").eq("student_id",id)]);setStudent(studentData||{});if(studentData){const{data}=await supabase.from("schools").select("*").eq("school_code",studentData.school_code).single();setSchool(data||{})}const records=[...(feeData||[]).filter(fee=>(fee.fee_type||"monthly")==="monthly").sort((a,b)=>months.indexOf(a.month)-months.indexOf(b.month)),...(feeData||[]).filter(fee=>fee.fee_type==="exam")];setFees(records);setSelectedExam(records.find(fee=>fee.fee_type==="exam")?.exam_fee_id||"");setLoading(false)})()},[id]);
  const paid=useMemo(()=>fees.filter(fee=>fee.status==="Paid").length,[fees]),exams=fees.filter(fee=>fee.fee_type==="exam"),visible=view==="monthly"?fees.filter(fee=>(fee.fee_type||"monthly")==="monthly"):exams.filter(fee=>fee.exam_fee_id===selectedExam);
  return <main className="fees-page-shell"><header className="finance-brand"><img src={school.school_logo||student.school_logo||"/brand-mark.svg"} alt=""/><div><small>MY SCHOOL · CODE {student.school_code||"—"}</small><h1>{school.school_name||student.school_name||"School fees"}</h1><p>{student.name||"Student"} · Class {student.class||"—"}-{student.section||"—"} · Roll {student.roll||"—"}</p></div><ReceiptIndianRupee/></header><section className="fees-premium-card"><div className="fees-title"><div><small>PAYMENT OVERVIEW</small><h2>My fee ledger</h2></div>{loading&&<span className="sync-badge">Loading…</span>}</div><div className="fees-summary premium-fee-summary"><div><CalendarCheck/><span><b>{paid}</b><small>Paid entries</small></span></div><div><Clock3/><span><b>{fees.length-paid}</b><small>Pending entries</small></span></div><div><CircleDollarSign/><span><b>{fees.length}</b><small>Total entries</small></span></div></div><div className="fee-ledger-tabs"><button className={view==="monthly"?"active":""} onClick={()=>setView("monthly")}>Monthly</button><button className={view==="exam"?"active":""} onClick={()=>setView("exam")}>Exam</button></div>{view==="exam"&&<select className="exam-fee-select" value={selectedExam} onChange={event=>setSelectedExam(event.target.value)}>{exams.map(fee=><option key={fee.id} value={fee.exam_fee_id}>{fee.title||fee.month}</option>)}</select>}<div className="premium-fee-grid">{visible.map(fee=>{const base=Number(fee.amount||0),carry=Number(fee.carried_due||0),total=base+carry,paidAmount=Math.min(total,paidFor(fee)),balance=Math.max(0,total-paidAmount);return <article key={fee.id} className={fee.status==="Paid"?"is-paid":"is-pending"}><div className="fee-month"><small>{fee.fee_type==="exam"?"EXAM FEE":"MONTH"}</small><b>{fee.title||fee.month}</b><strong>₹{base.toLocaleString("en-IN")}</strong><small>Previous dues ₹{carry.toLocaleString("en-IN")}</small><b>Total payable ₹{total.toLocaleString("en-IN")}</b><b>Total paid ₹{paidAmount.toLocaleString("en-IN")}</b><small>Balance due ₹{balance.toLocaleString("en-IN")}</small></div><div className="fee-state"><span></span><b>{fee.status}</b></div><div className="fee-date"><small>PAYMENT DATE</small><b>{fee.paid_at?new Date(fee.paid_at).toLocaleDateString("en-IN"):"Not paid"}</b></div></article>})}</div></section></main>;
}
