import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "../supabaseClient";
import { FaTimes } from "react-icons/fa";
import "./StudentResult.css";

export default function StudentResult(){
  const {studentId}=useParams(); const [examList,setExamList]=useState([]); const [results,setResults]=useState([]); const [selectedExam,setSelectedExam]=useState(false); const [examName,setExamName]=useState(""); const [student,setStudent]=useState({}); const [school,setSchool]=useState({});
  useEffect(()=>{(async()=>{const {data:studentData}=await supabase.from("students").select("*").eq("id",studentId).single(); setStudent(studentData||{}); if(studentData){const {data:schoolData}=await supabase.from("schools").select("*").eq("school_code",studentData.school_code).single(); setSchool(schoolData||{school_name:studentData.school_name,school_logo:studentData.school_logo});} const {data}=await supabase.from("results").select("*").eq("student_id",studentId); const {data:allTypes}=await supabase.from("exam_types").select("*"); const types=(allTypes||[]).filter(e=>!e.school_code||e.school_code===studentData?.school_code); const names=Object.fromEntries(types.map(e=>[e.id,e.name])); setExamList(Object.values((data||[]).reduce((a,i)=>(a[i.exam_type_id]={...i,exam_name:names[i.exam_type_id]||"Examination"},a),{})));})()},[studentId]);
  const openResult=async(examId,name)=>{setExamName(name);const{data}=await supabase.from("results").select("*").eq("student_id",studentId).eq("exam_type_id",examId);setResults(data||[]);setSelectedExam(true)};
  const total=results.reduce((s,i)=>s+Number(i.marks||0),0); const totalMax=results.reduce((s,i)=>s+Number(i.max_marks||100),0); const percent=totalMax?total/totalMax*100:0;
  return <div className="result-page"><div className="result-page-heading"><small>ACADEMIC RECORD</small><h2 className="page-title">Student Results</h2><p>{student.name||"Student"} · {school.school_name||student.school_name||"School"}</p></div>{examList.length===0?<div className="result-empty">Result Not Available</div>:<div className="exam-btn-box">{examList.map(exam=><button key={exam.exam_type_id} className="exam-btn" onClick={()=>openResult(exam.exam_type_id,exam.exam_name)}>{exam.exam_name}</button>)}</div>}{selectedExam&&<div className="overlay"><div className="marksheet"><button className="result-close" onClick={()=>setSelectedExam(false)} aria-label="Close"><FaTimes/></button><div className="marksheet-brand"><img src={school.school_logo||student.school_logo||"/brand-mark.svg"} alt=""/><div><small>OFFICIAL RESULT</small><h2 className="school-name">{school.school_name||student.school_name||"School"}</h2><p>{student.name} · Class {student.class}-{student.section} · Roll {student.roll}</p></div></div><h3 className="exam-title">{examName} Examination</h3><div className="table result-view-table"><div className="row header"><div>Subject</div><div>Obtained</div><div>Full Marks</div></div>{results.map(item=><div className="row" key={item.id}><div>{item.subject}</div><div>{item.marks}</div><div>{item.max_marks||100}</div></div>)}</div><div className="summary"><span><small>TOTAL</small><b>{total} / {totalMax}</b></span><span><small>PERCENTAGE</small><b>{percent.toFixed(2)}%</b></span></div><button className="print" onClick={()=>window.print()}>Print Result</button></div></div>}</div>;
}
